apiVersion: v1
kind: Service
metadata:
  name: deployer
  labels:
    app: deployer
    env: production
spec:
  selector:
    app: deployer
    env: production
  ports:
    - name: http
      port: 80
      targetPort: 8080
      protocol: TCP
